interface MetadataInput {
  productName: string;
  summary: string;
  keyFeatures: string[];
  overall: number;
  uxScore: number;
  performanceScore: number;
  featureScore: number;
  valueScore: number;
}

export function generateVideoMetadata(input: MetadataInput) {
  const title = `"${input.productName}" Review — AI-Powered Analysis`;

  const scoreSection = [
    `Overall: ${input.overall}/10`,
    `UX: ${input.uxScore}/10`,
    `Performance: ${input.performanceScore}/10`,
    `Features: ${input.featureScore}/10`,
    `Value: ${input.valueScore}/10`,
  ].join(" | ");

  const description = [
    input.summary,
    "",
    `Key Features: ${input.keyFeatures.join(", ")}`,
    "",
    `Scores: ${scoreSection}`,
    "",
    "This review was generated by Agentic Reviewer — an autonomous AI-powered product review pipeline.",
    "",
    "#SaaSReview #B2BSoftware #AIReview",
  ].join("\n");

  const tags = [
    input.productName,
    "SaaS review",
    "B2B software",
    "AI review",
    "software review",
    "product review",
    ...input.keyFeatures.slice(0, 5),
  ];

  return { title, description, tags };
}
