package distribute

import (
	"fmt"
	"strings"
)

// GenerateVideoMetadata produces a title, description, and tags for a product
// review video, following the same logic as the TypeScript generateVideoMetadata.
func GenerateVideoMetadata(productName, summary string, keyFeatures []string, scores map[string]float64) (title, description string, tags []string) {
	overall := scores["overall"]

	title = fmt.Sprintf("%s Review — %.1f/10 | Agentic Reviewer", productName, overall)
	if len(title) > 100 {
		title = fmt.Sprintf("%s — %.1f/10 | Review", productName, overall)
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("%s — AI-Powered Product Review\n\n", productName))
	sb.WriteString(summary)
	sb.WriteString("\n\n")

	if len(keyFeatures) > 0 {
		sb.WriteString("Key Features:\n")
		for _, f := range keyFeatures {
			sb.WriteString(fmt.Sprintf("- %s\n", f))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("Scores:\n")
	sb.WriteString(fmt.Sprintf("- Overall: %.1f/10\n", overall))
	if v, ok := scores["uxScore"]; ok {
		sb.WriteString(fmt.Sprintf("- UX: %.1f/10\n", v))
	}
	if v, ok := scores["performanceScore"]; ok {
		sb.WriteString(fmt.Sprintf("- Performance: %.1f/10\n", v))
	}
	if v, ok := scores["featureScore"]; ok {
		sb.WriteString(fmt.Sprintf("- Features: %.1f/10\n", v))
	}
	if v, ok := scores["valueScore"]; ok {
		sb.WriteString(fmt.Sprintf("- Value: %.1f/10\n", v))
	}

	sb.WriteString("\n---\nGenerated by Agentic Reviewer — Autonomous B2B Product Reviews")

	description = sb.String()

	tags = []string{
		productName,
		"SaaS review",
		"B2B software",
		"product review",
		"AI review",
		"software review",
		"agentic reviewer",
	}

	// Add features as tags (max 3 extra).
	for i, f := range keyFeatures {
		if i >= 3 {
			break
		}
		tags = append(tags, strings.ToLower(f))
	}

	return title, description, tags
}
